"""initial schema

Revision ID: ca1e9af733ce
Revises: 
Create Date: 2026-03-24 19:43:03.783340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1e9af733ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_nodes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('field_list_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_field_list_bindings_list_id'))

    with op.batch_alter_table('field_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_field_templates_active'))
        batch_op.drop_index(batch_op.f('idx_field_templates_field_name'))

    with op.batch_alter_table('instance_type_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_instance_type_fields_key'))
        batch_op.drop_index(batch_op.f('idx_instance_type_fields_template'))

    with op.batch_alter_table('managed_list_item_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_managed_list_item_links_child'))
        batch_op.drop_index(batch_op.f('idx_managed_list_item_links_parent'))

    with op.batch_alter_table('managed_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_managed_list_items_list_parent'))
        batch_op.drop_index(batch_op.f('idx_managed_list_items_parent_item_id'))

    with op.batch_alter_table('managed_list_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_managed_list_links_child'))
        batch_op.drop_index(batch_op.f('idx_managed_list_links_parent'))

    with op.batch_alter_table('managed_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uix_managed_lists_code'))

    with op.batch_alter_table('object_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_object_fields_template_id'))

    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_objects_id_full'))

    with op.batch_alter_table('relation_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_relation_types_inverse'))
        batch_op.drop_index(batch_op.f('idx_relation_types_key'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relation_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_relation_types_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('idx_relation_types_inverse'), ['inverse_relation_type_id'], unique=False)

    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_objects_id_full'), ['id_full'], unique=True)

    with op.batch_alter_table('object_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_object_fields_template_id'), ['field_template_id'], unique=False)

    with op.batch_alter_table('managed_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uix_managed_lists_code'), ['code'], unique=True)

    with op.batch_alter_table('managed_list_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_managed_list_links_parent'), ['parent_list_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_managed_list_links_child'), ['child_list_id'], unique=False)

    with op.batch_alter_table('managed_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_managed_list_items_parent_item_id'), ['parent_item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_managed_list_items_list_parent'), ['list_id', 'parent_item_id'], unique=False)

    with op.batch_alter_table('managed_list_item_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_managed_list_item_links_parent'), ['parent_item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_managed_list_item_links_child'), ['child_item_id'], unique=False)

    with op.batch_alter_table('instance_type_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_instance_type_fields_template'), ['field_template_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_instance_type_fields_key'), ['instance_type_key'], unique=False)

    with op.batch_alter_table('field_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_field_templates_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_field_templates_active'), ['is_active'], unique=False)

    with op.batch_alter_table('field_list_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_field_list_bindings_list_id'), ['list_id'], unique=False)

    with op.batch_alter_table('category_nodes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
